# Generated by Django 5.1.5 on 2025-01-21 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='data_urodzenia',
        ),
        migrations.RemoveField(
            model_name='autor',
            name='narodowosc',
        ),
    ]
