# Generated by Django 5.1.5 on 2025-01-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0002_remove_autor_data_urodzenia_remove_autor_narodowosc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ksiazka',
            name='data_publikacji',
        ),
        migrations.AddField(
            model_name='ksiazka',
            name='rok_publikacji',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
