# Generated by Django 5.1.2 on 2025-01-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folder_aplikacji', '0003_remove_ksiazka_data_publikacji_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='czytelnik',
            options={'ordering': ['uzytkownik__username']},
        ),
        migrations.AlterModelOptions(
            name='ksiazka',
            options={'ordering': ['tytul']},
        ),
        migrations.AlterModelOptions(
            name='wypozyczenie',
            options={'ordering': ['data_wypozyczenia']},
        ),
    ]
